### ISSUE TITLE
Version 0.12.0 - verbatim HTML: does not copy apostrophe and quotes verbatim in <script>

### ISSUE THREAD

**Issue by hmf** [planet42/Laika#106]
I retested my output and issue #93 does not seem to be solved. 8-( I get the same output. 
I have checked and am using the `withRawContent` flag. Would it be possible to confirm that 0.12.0 has the change referred to in  #93?

I was unsure if I should *reopen* the original. If so I will close this one and comment on the original ticket.

TIA

**Comment by jenshalm** [comment]
It was fixed with this commit: https://github.com/planet42/Laika/commit/1bf721dc49c18d1dbe9bd364d172c7cf32d1e137

As you can see I added two tests, one for the parsing and one for the rendering and they are green since the fix.

The only condition is (in line with the original Markdown spec) that the script tag must be inside a verbatim HTML block, where the entire block is enclosed in a root tag. It does not work when it's in the middle of plain text.

Did you add `withRawContent` to both parsers, Markdown and RST? If one is off the parser might get confused.

**Comment by jenshalm** [comment]
And some other general idea: I don't know the exact workflow of your tool, but now since you have separate parsing and rendering steps anyway, you could also programmatically inject the script into the tree you pass from the parser to the renderer, without the need to process or generate the input files and add script tags to them.

**Comment by hmf** [comment]
I  may be doing something wrong so I set-up the last example I last shared. The [code I am using](https://gitlab.com/hmf/srllab/blob/test_laika12/sdk/src/srllab/LaikaTest.scala#L61) seems to be correct ( I also tried with Markdown only):

```scala
    val parser = MarkupParser
      .of(Markdown)
      .withRawContent
      .using(GitHubFlavor)
      .io(blocker)
      .parallel[IO]
      .withAlternativeParser(MarkupParser.of(ReStructuredText).withRawContent)
      .build

    val renderer = Renderer
      .of(HTML)
      .withConfig(parser.config)
      .withMessageLevel(level)
      .io(blocker)
      .parallel[IO]
      .build
```

The [Markdown file](https://gitlab.com/hmf/srllab/blob/test_laika12/sdk/docs/mdoc/introduction/overview.md) simply has the HTML embedded in it. I generate the output and get the HTML file with the snippet shown below (see [overview.zip](https://github.com/planet42/Laika/files/3845963/overview.zip)).

I see that you have set-up tests also so I don't know if the set-up or source are wrong. Any ideas?

```
<!DOCTYPE html>
<html ="en">
    <head>
        <meta charset="UTF-8">
        <title><span class="sectionNumber">1.2 </span>Overview</title>
        <link href="../css/bootstrap.css" rel="stylesheet">
        <link href="../css/docs.css" rel="stylesheet">
        <!-- Plotly.js -->
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <!-- <script src="https://cdn.plot.ly/plotly-1.41.3.min.js"></script> -->
    </head>
    <body>
        <div class="toc">
          <p class="title">Contents</p>
          <ul>
            <li>
              <p class="toc level1">introduction</p>
              <ul>
                <li><span class="toc level2"><a href="installation.html"><span class="sectionNumber">1.1 </span>Installation</a></span></li>
                <li><span class="toc level2 active"><span class="sectionNumber">1.2 </span>Overview</span></li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="content">
            <h1 id="overview" class="title"><span class="sectionNumber">1.2 </span>Overview</h1>
            <p>Add documentation</p>
            <div style="width:100%; height:100%; text-align:center;">
              <div id="myDiv3"><!-- Plotly chart will be drawn inside this DIV --></div>
              <script type="text/javascript" defer>
                <!-- JAVASCRIPT CODE GOES HERE -->
                    var trace1 = {
                      x: [1, 2, 3, 4],
                      y: [10, 15, 13, 17],
                      mode: &#39;markers&#39;,
                      type: &#39;scatter&#39;
                    };
                                               
                    var trace2 = {
                      x: [2, 3, 4, 5],
                      y: [16, 5, 11, 9],
                      mode: &#39;lines&#39;,
                      type: &#39;scatter&#39;
                    };
                                               
                    var trace3 = {
                      x: [1, 2, 3, 4],
                      y: [12, 9, 15, 12],
                      mode: &#39;lines+markers&#39;,
                      type: &#39;scatter&#39;
                    };
                                               
                    var data = [trace1, trace2, trace3];
                                               
                    Plotly.newPlot(&#39;myDiv3&#39;, data);
              </script>
              <p style="text-align:center; font-weight: bold;">
                Figure 3: Embedded scatter plot example via an inlined script
              </p>
            </div>
        </div>
    </body>
</html>
```

**Comment by hmf** [comment]
In regards to:

>  programmatically inject the script into the tree you pass from the parser to the renderer

MDoc does quite a bit behind the scene so I would avoid that. This may come in handy for other things though. 

Thanks for the feedback.

**Comment by jenshalm** [comment]
Ah, that's because Laika only looks for `<script>` tags without attributes, which is not optimal. That would be another fix for 0.12.1. I'll create a ticket in the evening.

MDoc should not interfere in any way after parsing has happened. It would also avoid you needing to wait for 0.12.1. :-) If you have questions about how exactly you can do this, I can show an example.

**Comment by hmf** [comment]
> That would be another fix for 0.12.1. I'll create a ticket in the evening.

Appreciate your time and effort. I will wait for 0.12.1. 

> MDoc should not interfere in any way after parsing has happened.

[MDoc](https://github.com/scalameta/mdoc) is not my project. It is the preprocessor based on [Scalameta](https://scalameta.org/mdoc/) that I am using. What I meant is that it is not realistic for me to implement that functionality to be used in Laika's rendering.  8-}

Can/should I close this?

**Comment by jenshalm** [comment]
The way I understand the workflow is that MDoc reads Markdown, processes Scala code in it and then spits out Markdown again. The output from MDoc will then be fed to Laika as input. Once you have the tree in memory, MDoc is completely out of the picture and you could just generate a `HTMLScriptElement` node and insert it into the tree. The rendering of the final tree is pure Laika business, or am I missing something?

Otherwise, yes, you can close this one. I will track it with a more narrow description in a new one.

**Comment by hmf** [comment]
Your description of workflow of MDoc + Laika is correct. Indeed, all rendering is left to Laika. 
But generating a `HTMLScriptElement` node and inserting it into the tree poses a problem: I need to encode this in the Markdown document.  This may imply other issues I am not aware of. I therefore prefer Laika do this. 8-) 

Ok, will close. Thank you.
