### ISSUE TITLE
Cross Compile for Scala 2.11

### ISSUE THREAD

**Issue by grahamar** [planet42/Laika#17]
Support for Scala 2.11 would be really useful

**Comment by sirthias** [comment]
+1 on an update.
Also to show that the project is still alive.
I think Laika is a great basis for all kinds of things, it'd be a shame if it withered away... :)

**Comment by jenshalm** [comment]
Sorry for the lack of updates. Laika is definitely not dead, but very obviously on hiatus.

I moved to London in autumn and now for a while a lot of spare time is consumed by contributing to Finch (which gets used in my current contract), but I expect to be able to resume working on Laika in March. 

The timing was a bit unfortunate, when I had to stop in August I was very close to the release with PDF support. The only things missing are: 1) expand the test suite to cover all the new features, 2) create a default XSL-FO template that leads to a professional layout when transformed via Apache FOP and 3) documentation. So it's probably about 5 full days of work.

The initial fast pace of Laika development was caused by me having a sabbatical and working on it almost full-time for a while. But since then, as long as I am the only maintainer, there will always be gaps. In particular before the 1.0 release where every update is a big feature addition.

**Comment by sirthias** [comment]
Thanks for the update, Jens! Much appreciated.
I just wanted to say that I use Laika in a recent project of mine an really like it! It does exactly what it needs to do, and it does it fast.
Great work!

**Comment by jenshalm** [comment]
That's cool, it's always nice to hear about real-world usages. The downside of having extensive documentation and few bugs is that you don't hear that much from your users. :-)

**Comment by sirthias** [comment]
Absolutely. No issues so far.
There might be a PR coming though, with small additions here and there. Nothing much so far....

**Comment by ferranjr** [comment]
+1 :)

**Comment by drewhk** [comment]
I also love it, really good work!
