### ISSUE TITLE
Code blocks with newlines are not parsed correctly

### ISSUE THREAD

**Issue by noelwelsh** [planet42/Laika#219]
A code block containing a newline is parsed (I think) as normal text. In particular `[A]` will be interpreted as a link and parsing will fail with an "unresolved link id reference". The following code blocks demonstrate the issue:

Parses okay

```scala
List[Int]
```

Parses okay

```scala
Either[String, A]
```

[error]   [12]: unresolved link id reference: int
[error] 
[error]   List[Int]
[error]       ^
[error] 
[error]   [14]: unresolved link id reference: string, a
[error] 
[error]   Either[String, A]
[error]         ^
[error] 

```scala
List[Int]

Either[String, A]
```

Tested in both Laika 0.18 and 0.17.1

I can post a complete project if useful.

**Comment by jenshalm** [comment]
Hello Noel, I would not need a complete project, but I would need to see the original markup you are using which is not clear from your examples. First, I assume this is Markdown? (Laika also supports reStructuredText). If it is Markdown, are these code blocks demarcated with triple backticks or classic Markdown with the code indented by 4 spaces? 

I think it would be sufficient if you would change your code blocks above to be surrounded by ```` ```markdown ```` markers instead.

**Comment by noelwelsh** [comment]
```markdown
```scala
List[A]

Either[String, A]
```
```

**Comment by jenshalm** [comment]
Ah, I assume that you haven't enabled `GitHubFlavor` then. 

The backticks were not part of the original, classic Markdown and are not enabled by default, even though they are used by most documentation writers these days. 

The confusing bit was just that you get different results depending on whether you have newlines or not, which is, funnily enough, also expected behaviour. In the case of one line, it is reading parts as literal text enclosed by backticks, ignoring any markup between them, in the second it isn't as the blank line makes it two different paragraphs and inline markup does not span multiple paragraphs.

To get it working, if you are using the library API, create the parser like this:
```scala
val parser = MarkupParser
  .of(Markdown)
  .using(GitHubFlavor, SyntaxHighlighting)
  .build
```

In Laika's sbt plugin it is simply:
```scala
laikaExtensions := Seq(GitHubFlavor, SyntaxHighlighting)
```

`SyntaxHighlighting` is optional if you want to use external, JS-based tools.

**Comment by noelwelsh** [comment]
Ok, thanks. You may want to make this a bit more prominent in the documentation. I don't think many users will be experts on the nuances of different Markdown formats.

**Comment by jenshalm** [comment]
Yes, I tend to agree and see what I can do to make it clearer. The choice makes sense internally, as each format by default is mostly what's in the original spec, but it's probably counter-intuitive for many users. 

The situation around Markdown is sadly quite messy, as what most people are using on sites like this one nowadays is actually CommonMark, a derivative of the original Markdown that Markdown's creator did not permit to be called Markdown...
