### ISSUE TITLE
Vertical bar (|) inside code inside table breaks the table

### ISSUE THREAD

**Issue by TomasMikula** [planet42/Laika#242]
Hi,

when using inline code in a table, vertical bar `|` inside the code is still considered as delimiting the table.

Markdown:

```
|  header  |
| -------- |
|  `A | B` |
```

HTML:

```html
<table>
          <thead>
            <tr>
              <th>header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>`A</td>
            </tr>
          </tbody>
        </table>
```

---

Markdown:

```
|     header     |
| -------------- |
|  `List[A] | B` |
```

Error:

```
[error]   [1140]: unresolved link id reference: a
[error] 
[error]   `List[A] | B` |
[error]           ^
```

**Comment by jenshalm** [comment]
Hello Tomas, this is unfortunately impossible to improve due to the way text markup parsers work: they are two-phase parsers where the block-level parsers know nothing about inline parsers (and for a whole range of reasons I don't want to bore you with it's not really feasible to change this).

Instead you need to explicitly escape those characters:
```markdown
|  header  |
| -------- |
|  `A \| B` |
```

If you try the Markdown editor here on GitHub, it behaves in the same way.

**Comment by TomasMikula** [comment]
> If you try the Markdown editor here on GitHub, it behaves in the same way.

Ah, right.

Thank you for the quick response.
