### ISSUE TITLE
Unable to resolve references to links within callout sections

### ISSUE THREAD

**Issue by dpdearing** [planet42/Laika#255]
When generating a PDF document from a Markdown file, if the [`@:callout`](https://planet42.github.io/Laika/0.18/07-reference/01-standard-directives.html#callout) text includes a link (in my case, to another section within the same document), I get the following error message:

```
[error] (docs / laikaPDF) laika.parse.markup.DocumentParser$InvalidDocuments: One or more invalid documents:
[error] /MyDocument.md
[error]
[error]   [53]: Unresolved internal reference to 'section in same document'
...
```

Where the document is `MyDocument.md` and I am trying to link to a section header named "Section in Same Document"

Is this known or expected behavior?

I am using the `LaikaPlugin` for sbt: `org.planet41:laika-sbt:0.18.1`

**Comment by jenshalm** [comment]
Yes, this is a known bug, that I somehow did not transfer from my local tracker up to here. It's possible to fix it, but most likely in a binary-breaking way, so I'll schedule it for 0.19.0 now. 

I think it's something that never worked yet, but also somehow never got reported (I only found this out myself a few weeks ago). Since you ran into this now, I'll use your issue for tracking this here now. Thanks for reporting.
