### ISSUE TITLE
Add `<link rel="canonical" href="...">` to versioned pages

### ISSUE THREAD

**Issue by armanbilge** [planet42/Laika#264]
We've been discussing this in https://github.com/http4s/http4s/issues/5715#issuecomment-1059806899.

The basic idea is that when there are multiple versions of the same page, a canonical url helps search engines index them as a single entry which is good for SEO. This technique is adopted by e.g. https://haha.readthedocs.io/en/latest/canonical.html

At first glance, this seems easy to support by adding an additional option to the `Versions` config where the canonical version can be specified and updating the template. Thinking a bit harder, it's not obvious what to do about pages that are present in the current version but not present in the canonical version.

**Comment by jenshalm** [comment]
Adding it to the configuration would be fairly easy. And I think for pages not being present it should probably not get rendered.

However, I wonder how well this will work for users, given that we don't render a `/latest` output. When you point to a concrete version, you would need to update all branches whenever this config changes (e.g. when there is a new major/minor release).

**Comment by armanbilge** [comment]
> And I think for pages not being present it should probably not get rendered.

Right, except how would the e.g. 0.1 branch know that the file is not present in the 0.2 branch? That part seemed complicated to me 🤔 

> When you point to a concrete version, you would need to update all branches whenever this config changes (e.g. when there is a new major/minor release).

Yes, I was thinking about that too. I need to research more about search engines interpret this, but maybe it can be daisy-chained. E.g. if 0.1 canonicals point to 0.2, but when you follow to 0.2 the canonicals point to 0.3. Then it would be fine 😆

**Comment by jenshalm** [comment]
> Right, except how would the e.g. 0.1 branch know that the file is not present in the 0.2 branch? That part seemed complicated to me 🤔

Ah yes, that's the tricky bit, as on a branch you would not keep the `versionInfo.json` up-to-date, which is exactly the only way it could know which ones are present... Keeping those always in sync feels very error-prone and cumbersome.

**Comment by jenshalm** [comment]
I've now spent some time on conceptional planning for some of the remaining 0.19 features - and I think there are limited options for supporting this functionality, apart from one which might appear a bit surprising, more on that below.

I've also tried to find some prior art in other tools which is difficult as versioning is not commonly supported in doc tools. I did, however, see that many tools support a form of manual configuration for canonical pages - in the frontmatter of the markup document. I think this is useful to have, even when it's mostly automated for versioned pages, since you might want to set this in other scenarios, too, or potentially overwrite the auto-setting for versioning (which is necessary if the page's path has changed for example). So I plan to add a `canonicalLink` property to the existing `laika.metadata` structure which supports settings like `author` or `datePublished`.

Now for the automation for versioned pages, I do not consider to support this in the statically rendered output for all the problems we discussed above: there does not seem to be a way to implement this without asking the user to keep the version configuration up-to-date on maintenance branches, which is not a good idea - first because it is error-prone and second because it would only be necessary for this one feature while everything else works in a more convenient way.

There is a plan B though: JavaScript! 🙂 I've checked some crawler documentation and at least the one from Google executes JavaScript and they even show an example for how to inject meta tags dynamically. And this would be surprisingly easy to implement: when the `version.json` executes it knows all the available pages and it would just require a few lines of extra code to inject the `link` tags from there. So the DX would be great because all the user needs to do is to set a single flag on the main branch.

Let me know what you think.

**Comment by armanbilge** [comment]
Thank you so much for thinking about this!

> I've checked some crawler documentation and at least the one from Google executes JavaScript and they even show an example for how to inject meta tags dynamically.

Sure, given the constraints this is not an unreasonable solution :) although you'd forgive me for being at least a little bit skeptical! Do you have some of those references you looked at?

I'd hope that even if the page content doesn't change (which may be indicated by an ETag), browsers would still re-index it and see the dynamic updates?

> there does not seem to be a way to implement this without asking the user to keep the version configuration up-to-date on maintenance branches, which is not a good idea

Related: in Ross's versioned documentation wishlist https://github.com/typelevel/sbt-typelevel/issues/100, he includes this nice-to-have:

> EOL versions can easily point to a maintained version

I guess the answer to this is JavaScript as well :) esp. if you want even your oldest docs to continue pointing to the latest maintained version.

I was going to suggest you can publish an EOL branch one last time, so at least it points to the next branch up. But, this would still be somewhat annoying and require config, and old docs would only "daisy-chain" their way up to the latest instead of pointing directly. Also, I'd be skeptical about daisy-chained canonicals as well :) OTOH, at least it would be static.

Overall, I think you're right. A JS-based solution delivers the best experience for both devs and docs-readers. In a world full of SPAs hopefully search engines should manage just fine.

> So I plan to add a `canonicalLink` property to the existing `laika.metadata`

👍 that sounds fantastic.

**Comment by jenshalm** [comment]
> Do you have some of those references you looked at?

https://developers.google.com/search/docs/advanced/javascript/javascript-seo-basics

> EOL versions can easily point to a maintained version

Yes, I think this should be fairly straightforward once all the other pieces are in place. I can even imagine this as a configurable Helium feature that injects a yellow warning callout at the top of the page for EOL versions.

Btw. this discussion made me think about using `/latest` as a path segment for the latest stable version for Laika's own docs, instead of `/0.18` - to obtain a permanent, canonical URL for content. Some people might try to manually type `0.18` in the browser, but I feel like this should not happen very often.

**Comment by armanbilge** [comment]
> Btw. this discussion made me think about using /latest as a path segment for the latest stable version for Laika's own docs

Right. This is similar to Ross's `/stable` from https://github.com/typelevel/sbt-typelevel/issues/100.

Actually, with this canonical thing in place ... would there be harm in publishing two identical copies of the docs, one at `/latest` or `/stable` or whatever, and a second at `/0.18`? That way when 0.19 ships it can replace the stuff at `/latest` without erasing the 0.18 docs from existence, since there's the other copy at `/0.18`.

**Comment by jenshalm** [comment]
Would you erase anything? When 0.19 ships that would be under `/latest` where 0.18 used to be and the previous release would be under a new segment `/0.18`.

**Comment by armanbilge** [comment]
Right, so then 0.19 is under `/latest`. But what happens when e.g. 0.20 comes around? I guess I'm confused about how the 0.19 docs relocate themselves to `/0.19` at that time, without having to republish from that branch.

**Comment by jenshalm** [comment]
Ah, yes, the actual act of making that happen, I was only thinking about the theory. 🙂 
Would the need to re-publish be that bad? Not sure how this could be automated.
In any case, double-publish would be a separate feature-request, with a separate ticket. 🙂 (and maybe beyond scope for 0.19 - not sure).

**Comment by armanbilge** [comment]
> Would the need to re-publish be that bad?

Slightly annoying, but not the end of the world :) If we do this, then I think we shouldn't rely on JavaScript to set canonicals and EOL banners, since you can do it statically at the time you do that re-publish to make that old branch no longer latest.

**Comment by jenshalm** [comment]
It could get messed up the moment something on the main branch changes, though. It would be the state of the world at the point of creating the maintenance branch, frozen in time. You could get dead links this way, for example, even though for most practical purposes it's not that likely.
