### ISSUE TITLE
Code samples in manual lack imports

### ISSUE THREAD

**Issue by valencik** [planet42/Laika#274]
First off thank you for creating this project, I'm really excited to use it :)

I did however run into some confusion trying to get setup.
The documentation does not mention the need for imports either in text or in the examples.
As a result I was getting errors like:
> "error: not found: value Theme"

and

> error: not found: value Helium
    laikaTheme := Helium.defaults

All I needed was
```
import laika.theme.Theme
```

I think, the earliest examples in the documentation should explicitly show the relevant imports.

Happy to submit a PR if folks think it would be worthwhile.

**Comment by jenshalm** [comment]
Welcome, and sorry for the late response. I think this is a perfectly reasonable request, things like this surface because there has been surprisingly little feedback for the manual for a project with 300+ stars. And I rarely have to use my own manual when using Laika, so I did not notice either. 🙂 

I'd be happy to accept a PR that addresses this in the way you described: Add imports to code samples that introduce new API and omit them when showing slight variations of the same code. You also don't need to cover the whole manual if if you don't have the time, I'm equally happy to just merge something that gets that improvement started.

I hope you don't mind I renamed the issue. It's not because it sounded somewhat broadly negative 🙂 - but more so that users know what this is actually about.
