### ISSUE TITLE
Render `@:api` directive like code (backtickified) ?

### ISSUE THREAD

**Issue by armanbilge** [planet42/Laika#285]
This is a very tiny, very personal preference :) In general I feel like code things such as APIs should be in backticks. This is how many existing docs are as well, and it would be nice to migrate them to use this directive.

Probably also applies to `@:source` directive, but I haven't tried that.

Thanks for considering!

**Comment by jenshalm** [comment]
I can have a look. I'm mildly worried it looks too similar too un-linked code spans then, but if that's not the case I can change it.

If not, the minimum I should do (and I just realized that when I checked the directive's impl) is to assign a class attribute to these kind of special links, e.g `<a class="api"...`) so that you can curlybracify it into backtickification with a single line of CSS as a default within sbt-typelevel, if that's something you'd find greentickable as a plan B.

**Comment by armanbilge** [comment]
> I'm mildly worried it looks too similar too un-linked code spans then

Yes, in my experience they do look the same unfortunately 😕 enabling CSS customization is a very reasonable fix as well 👍 

I do wonder  now if these should be rendered differently. Like an ordinary code span, except with a link icon or something to make it more obviously it's a link.

**Comment by jenshalm** [comment]
Yes, maybe. Nice thing is we can freely play around with it once the CSS classes are there, and then still change the default later. Since it's something I can do during the 0.19 maintenance cycle, I won't invest time before the release (beyond adding the class).
