### ISSUE TITLE
Styling PDF output

### ISSUE THREAD

**Issue by chuwy** [planet42/Laika#337]
Hey there! I think I need some help styling my PDF docs generated with Laika.

I have a basic table in Markdown, converting it to PDF with [default template](https://github.com/planet42/Laika/blob/master/io/src/main/resources/laika/helium/templates/default.template.fo) and following CSS:

```css
Cell {
  font-style: italic;

  text-align: center;
  color: #FF0000;
}
```

What I expect to see is the whole CSS being applied to all cells in the table, but in reality the font gets italic, but neither color nor alignment have an effect.

I tried [other table elements](https://planet42.github.io/Laika/latest/04-customizing-laika/04-document-ast.html#block-elements) with same result. I'm wondering if I miss some style being applied via other selector or styles are invalid.

How can I see the interim AST (or XML-FO) to debug the styling? How's the [content](https://github.com/planet42/Laika/blob/master/io/src/main/resources/laika/helium/templates/default.template.fo#L48) generated? Are there any templates for it?

**Comment by jenshalm** [comment]
This limitation stems from the fact that I appear to have interpreted the XSL-FO spec in a too strict way and that nobody has ever noticed this in the 6 years this feature exists. 🙂  CSS for PDF seems to be an underused feature, has not been changed or enhanced since its introduction in 2016 and rarely ever received feedback or bug reports so far. 

But whether this can actually be fixed also depends on the support in the underlying library (Apache FOP) which I'd need to verify first at some point. But let's get into the details:

* To avoid runtime errors Laika filters all attributes not supported by a specific element and follows the XSL-FO spec for that. You can see the list for `fo:table-cell` [here](https://www.w3.org/TR/xsl11/#fo_table-cell), and `color` and `text-align` are not in it.

* However, the spec also states that any attribute can be placed into any element, just that some are not **applied** to specific element types. They can still be inherited by child elements though, and Laika does not cater for this as I did not spot this rule back when I implemented this feature based on the spec.

* The filtering happens based on very simple lookup tables here: https://github.com/planet42/Laika/blob/main/core/shared/src/main/scala/laika/render/FOProperties.scala#L397

A potential fix should first verify that adding the two unsupported attributes from your example would actually work with Apache FOP and if yes, the fix would be to enhance the `FOProperties` trait to introduce a Set `inheritedAttributes` based on spec info here: https://www.w3.org/TR/xsl11/#prtab1 and add that Set to all Sets mapped to element names.

Regarding your other questions, yes you can inspect both, the AST or the interim XSL-FO, just by swapping the renderer, e.g. in the code below:
```scala
Transformer
  .from(Markdown)
  .to(PDF)
  ...
```
you would just replace `PDF` with either `AST` or `XSLFO` - just note that in this case the target is a directory, not a file, you get an `.txt` file per markup document for `AST` and an `.fo` file per markup document for `XSLFO`. 

In sbt you can run `laikaGenerate fo` or `laikaGenerate ast` respectively.

But the AST would not help you much in this case. The AST is generic (does not contain any specifics about a particular render format yet), the CSS is later applied in the render phase.
