### ISSUE TITLE
reStructuredText Option Lists Not Quite Right?

### ISSUE THREAD

**Issue by tundratim** [planet42/Laika#36]
I have been working with the RST plugin for GitBucket which makes use of Laika:

https://github.com/amuramatsu/gitbucket-rst-plugin

It seems to work fairly well, but gets lost with RST manpage-style option lists.  For example, see the "Options" section of this document:

http://gitbucket.tundraware.com:8080/tundra/tren/blob/master/tren.rst

Since the GitBucket plugin is really just a wrapper around Laika, I'm hoping you can provide some insight/fixes/configs to make this work.

Thanks,

**Comment by jenshalm** [comment]
Sorry, I somehow overlooked this ticket. If this is still of relevance, could you please add more detail? The link above does not work. Could you paste a simple snippet of rst, and then the expected and actual output?

**Comment by tundratim** [comment]
Oh, sorry, we moved the server to:

https://gitbucket.tundraware.com/tundra/tren/blob/master/tren.rst

You'll notice that the Options are being misrendered.  In talking to the gitbucket rst plugin dev, they say that they're just sending the rst of to your code for rendering and then returning the results.

Any thoughts?

**Comment by jenshalm** [comment]
It might be that you fool the parser by indenting the option list, which is rst syntax for a blockquote. So first attempt would be to remove the indentation left of the arguments. If that does not help you could have a look at the working tests for option lists here: https://github.com/planet42/Laika/blob/master/core/src/test/scala/laika/parse/rst/ListParsersSpec.scala#L427 and investigate whether they somehow differ from the syntax in your files.

**Comment by tundratim** [comment]
@jenshalm 

Outdenting the  options lists does not fix the problem.  Unfortunately, I don't know scala and cannot quite grok the test you pointed me to.

**Comment by jenshalm** [comment]
It might be that other tools interpret the spec more loosely or more flexibly.  Laika follows the spec very closely and does not aim to mimic other tools. If you look at the option list definition here: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#option-lists, you can see that it is very strict about what it accepts as an option list. When parsing an option list fails due to an unknown construct, Laika falls back to parsing it as something else, maybe as a list due to the leading `-`.

You can verify this by changing the left column to only contain simple options (e.g. `-v`) which should work and then adding back the more complex stuff to see at which point it breaks.

**Comment by tundratim** [comment]
@jenshalm 

With respect, I do believe there is possibly a problem with the Laika implementation.  I took the example provided in the docutils reference you provided previously and put it in a test repo.  You can see that it is not getting correctly rendered here: 



https://gitbucket.tundraware.com/tundra/testrepo/blob/master/test.rst

**Comment by amuramatsu** [comment]
I try to check option list parsing in Laika.

IMHO, if options list has 3 or more spaces between 'command-line option' and 'descriptions', Laika returns unexpected result.

https://github.com/amuramatsu/Laika/blob/issue-36-check/core/src/test/scala/laika/parse/rst/ListParsersSpec.scala#L487-L497

**Comment by tundratim** [comment]
If you go to the repo below, you'll see a variety of things I've tried - none of which work correctly.  The guy who wrote the GitBucket rst plugin, tells me that he's just passing along what Laika returns without further interpretation of the html.

**Comment by jenshalm** [comment]
Thanks to all for providing more detail. I will start with investigating based on the example from the rst spec, because that is indeed supposed to work. Once I've narrowed it down I will report back.

**Comment by jenshalm** [comment]
Ok, I just fixed a few things.

The issue discovered by @amuramatsu was tracked and fixed in #39. Note that this was a very isolated issue, even with the bug the option list got still parsed as an option list, it just had the description text unnecessarily wrapped in an QuotedBlock, so does not explain the issues of the original poster.

While re-reading the rst spec entry on option lists I also discovered that option arguments in angle brackets (e.g. `-a <in=out>`) were not supported. This has been tracked and fixed in #40.

But the issue by the original poster was more fundamental. I now suspect that the extended renderer for rst had not been installed. This is currently not well documented. But the HTML renderer in Laika is generic and does not know any specifics about markup syntax like Markdown and rst and does not support some of the more exotic tree elements like option lists out of the box, as this is a feature specific to rst. So apart from using a snapshot with the 2 bugfixes you'd also need to install the custom renderer as shown in the code snippet here: http://planet42.github.io/Laika/api/#laika.parse.rst.ExtendedHTML

I will close this issue, too, in a few days unless further option list issues surface in the meantime.

**Comment by jenshalm** [comment]
Closing this now, as the problems reported by the original poster should be solved by:

* Using a snapshot from master containing the fixes for #39 and #40 
* Installing the custom renderer as shown in the code snippet here: http://planet42.github.io/Laika/api/#laika.parse.rst.ExtendedHTML

Should you find further issues with reStructuredText option lists, please try to narrow them down first and then open a new ticket.

**Comment by tundratim** [comment]
Many thanks.  Will let you know if this fails to resolve he issue.
